name: Manual
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: choice
        options:
          - Hello
          - goodby
          - see you
          - hi!
        default: Hello
        required: true
        description: A cheerful world
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}" # 入力パラメータ「greetingの参照」